name: Packagist Auto Update

on:
  push:
    branches:
      - master
      
jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        run: |
          curl -X POST "https://packagist.org/api/update-package?username=baseciq&apiToken=82a55c62a99cb02ae9a80052c9a72f4d9f6bf1c9" \
            -d '{"repository":"https://github.com/baseciq/php-html-parser"}' \
            -H "Content-Type: application/json"
